UI_TEXT = {
    "page_title": "Visualització",
    "select_series": "Selecciona la sèrie a analitzar",
    "upload_button_text": "Puja un arxiu",
    "upload_instructions": "Arrossega i deixa anar un arxiu aquí o fes clic per pujar",
    "file_limits": "Màxim {} MB per arxiu.",
    "choose_plot": "Selecciona el gràfic",
    "plot_options": [
        "Sèrie original",
        "Sèrie per any",
        "STL",
        "Anàlisi de retards",
        "Boxplot d'estacionalitat",
    ],
    "choose_years": "Tria els anys a visualitzar",
    "stl_error": "No es pot realitzar la descomposició STL per a la sèrie seleccionada, prova un altre nivell d'agregació temporal.",
    "boxplot_error": "No es pot visualitzar un boxplot adequat per a la granularitat seleccionada.",
    "select_frequency": "Selecciona la freqüència",
    "frequency_options": ["Diària", "Setmanal", "Mensual"],
    "boxplot_titles": {
        "daily": "Boxplot diari",
        "weekly": "Boxplot setmanal",
        "monthly": "Boxplot mensual",
    },
    "sidebar_title": "Visualitzacions",
    "select_visualization": "Selecciona la visualització",
    "visualization_options": ["Exploració", "Previsió"],
    "select_temporal_grouping": "Selecciona l'agrupació temporal de les dades",
    "no_columns_to_filter": "No hi ha columnes per filtrar. Només s'ha detectat una sèrie",
    "temporal_analysis_error": "No es pot realitzar l'anàlisi temporal",
    "forecast_plot_title": "Gràfic de previsió",
    "select_series_to_plot": "Selecciona almenys una sèrie per graficar la previsió",
    "choose_date": "Tria una data",
    "error_visualization_title": "Visualització d'errors",
    "select_date_range": "Selecciona el rang de dates (columna datetime) per visualitzar els errors de previsió",
    "top_10_errors": "Top 10 errors percentuals absoluts",
    "show_median_or_mean": "Mostrar mediana o mitjana",
    "median_or_mean_options": ["Mediana", "Mitjana"],
    "median_option": "Mediana",
    "mean_option": "Mitjana",
    "mediana_mean_string_dict": {"Mediana": "mediana", "Mitjana": "mitjana"},
    "error_message": "L'error percentual absolut {} de la sèrie és de {}",
    "select_plots": "Selecciona els gràfics a mostrar",
    "plot_options_error": [
        "Box plot per horitzó",
        "Box plot per datetime",
        "Dispersió",
    ],
    "horizon_boxplot_title": "Box plot per horitzó",
    "horizon_warning": "El nombre de punts per horitzó és molt variable, revisa el teu procés de generació de previsions. Has de generar per a cada datetime la mateixa quantitat d'horitzons, fent forecast_origin=forecast_origin-horitzó amb tots els horitzons que vols preveure.",
    "datetime_boxplot_title": "Box plot per datetime",
    "select_temporal_aggregation": "Selecciona l'agregació temporal per al boxplot",
    "temporal_aggregation_options": ["Diari", "Mensual"],
    "axis_labels": {
        "date": "Data",
        "value": "Valor",
        "horizon": "Horitzó",
        "error": "Error percentual absolut",
    },
    "series_names": {
        "real": "Real",
        "forecast": "Previsió",
    },
    "error_types": {
        "perc_abs_err": "Error percentual absolut",
        "perc_err": "Error percentual",
        "abs_err": "Error absolut",
        "err": "Error",
        "weekday": "Dia de la setmana",
    },
    "preview_title": "Vista prèvia",
    "upload_file": "Puja un arxiu",
    "file_title": "Arxiu:",
    "file_name": "Nom de l'arxiu",
    "separator": "Separador",
    "decimal": "Decimal",
    "thousands": "Milers",
    "encoding": "Codificació",
    "date_format": "Format de data",
    "decimal_help": "p. ex., '.', ','",
    "thousands_help": "p. ex., ',', '.', ' '",
    "encoding_help": "p. ex., 'utf-8', 'latin1', 'ascii'",
    "date_format_help": "p. ex., '%Y-%m-%d', '%d/%m/%Y'",
    "load_data": "Carregar dades",
    "manage_files": "Gestionar arxius pujats",
    "separator_help": "p. ex., ',', ';', '|', '\\t'",
    "update_file": "Actualitzar arxiu",
    "remove_file": "Eliminar arxiu",
    "datetime_warning": "Les columnes 'datetime' o 'forecast_origin' no estan presents per calcular 'h'.",
    "f_column_missing": "La columna 'f' no està present, per tant no es calcularan els errors.",
    "exploration_mode": "El mode actual és 'Exploració', no es calcularan columnes de previsió ni errors.",
    "no_files_uploaded": "No s'han pujat arxius.",
    "choose_column": "Tria {}:",
    "add_selected_series": "Afegir sèrie seleccionada",
    "series_already_added": "La sèrie seleccionada ja està a la llista",
    "remove_all_series": "Eliminar totes les sèries seleccionades",
    "no_series_selected": "No s'han seleccionat sèries",
    "boxplot_by_horizon": "Box plot per horitzó",
    "boxplot_by_datetime": "Box plot per datetime",
    "scatter_plot": "Gràfic de dispersió",
    "temporal_grouping_options": [
        "Per hora",
        "Diari",
        "Setmanal",
        "Mensual",
        "Trimestral",
        "Anual",
    ],
    "hourly": "Per hora",
    "daily": "Diari",
    "weekly": "Setmanal",
    "monthly": "Mensual",
    "quarterly": "Trimestral",
    "yearly": "Anual",
    "visualization_not_implemented": "La visualització '{}' no està implementada. Si us plau, seleccioneu '{}' o '{}'.",
    "DAY_NAME_DICT": {
        0: "Dilluns",
        1: "Dimarts",
        2: "Dimecres",
        3: "Dijous",
        4: "Divendres",
        5: "Dissabte",
        6: "Diumenge",
    },
    "MONTH_NAME_DICT": {
        1: "Gener",
        2: "Febrer",
        3: "Març",
        4: "Abril",
        5: "Maig",
        6: "Juny",
        7: "Juliol",
        8: "Agost",
        9: "Setembre",
        10: "Octubre",
        11: "Novembre",
        12: "Desembre",
    },
    "ALL_DICT": {
        "Diari": {
            0: "Dilluns",
            1: "Dimarts",
            2: "Dimecres",
            3: "Dijous",
            4: "Divendres",
            5: "Dissabte",
            6: "Diumenge",
        },
        "Mensual": {
            1: "Gener",
            2: "Febrer",
            3: "Març",
            4: "Abril",
            5: "Maig",
            6: "Juny",
            7: "Juliol",
            8: "Agost",
            9: "Setembre",
            10: "Octubre",
            11: "Novembre",
            12: "Desembre",
        },
    },
    "day": "Dia",
    "month": "Mes",
    "select_filter_type": "Selecciona el tipus de filtre:",
    "datetime_filter": "Filtrar per datetime",
    "forecast_origin_filter": "Filtrar per origen de previsió",
    "both_filters": "Filtrar per ambdós",
    "select_datetime_range": "Selecciona el rang de datetime:",
    "select_forecast_origin_range": "Selecciona el rang d'origen de previsió:",
    "add_new_file": "Afegir nou arxiu",
    "aggregated_summary_title": "Resum d'errors",
    "select_top_10": "Selecciona el model per veure els 10 errors principals:",
    "best_error_message": "El millor model és '{}', amb un error percentual absolut de {}",
    "model_parameters": "Paràmetres del model",
    "message_forecast_baseline": "Previsió obtinguda dels models base en aquesta plataforma.",
    "warning_no_forecast": "No hi ha dades de previsió disponibles. Si us plau, entreneu primer el model.",
    "upload_forecast": "Previsió detectada de l'arxiu pujat.",
    "forecast_parameters": "Si us plau, especifiqueu els paràmetres de previsió:",
    "horizon": "Horitzó",
    "step_size": "Mida del pas",
    "n_windows": "Nombre de finestres",
    "explanation": "Veure explicació",
    "explanation_horizon": f"El **{'horitzó'}** és el nombre de passos de temps que es vol predir.",
    "explanation_step_size": f"La **{'mida del pas'}** és el nombre de passos de temps entre cada finestra de previsió.",
    "explanation_n_windows": f"El **{'nombre de finestres'}** és el nombre de finestres de previsió que es volen generar.",
    "documentation": "Veure documentació",
    "activate_button_train": "Activar previsió",
    "jinja_template": "Descarregar script de previsió",
    "downloaded": "Script descarregat amb èxit."
}
