version: 2
updates:
  - package-ecosystem: "pip" # Motor para detectar uv.lock
    target-branch: "feature/dependabot_uv"
    directories:
      - "/mango"
      - "/mango_autoencoder"
      - "/mango_calendar"
      - "/mango_dashboard"
      - "/mango_genetic"
      - "/mango_time_series"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependabot"
      - "uv-deps"
      - "python"