name: Publish mango time series to Pypi

on:
  push:
    tags:
      - 'ts*'

jobs:
  build:
    name: Build and publish to PyPI.
    defaults:
      run:
        working-directory: ./mango_time_series
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install build
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build binary wheel and source tarball
        run: |
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_mango_time_series_token }}
          packages_dir: ./mango_time_series/dist
