name: Publish mango autoencoder to Pypi

on:
  push:
    tags:
      - 'autoencoder*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'autoencoder')

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Build package
        run: uv build --sdist --wheel
        working-directory: autoencoder

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_AUTOENCODER_TOKEN }} dist/*
        working-directory: mango_autoencoder