name: Publish mango to Pypi

on:
  push:
    tags:
      - "mango_base*"

jobs:
  build:
    name: Build and publish to PyPI.
    defaults:
      run:
        working-directory: ./mango_base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install build
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build binary wheel and source tarball
        run: |
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          packages_dir: ./dist
