name: Publish mango time series to Pypi

on:
  push:
    tags:
      - 'ts*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Build package
        run: uv build --sdist --wheel
        working-directory: mango_time_series

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.pypi_mango_time_series_token }} dist/*
        working-directory: mango_time_series

