name: Publish mango code_mango_genetic to Pypi

on:
  push:
    tags:
      - 'code_mango_genetic*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/code_mango_genetic')

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Build package
        run: uv build --sdist --wheel
        working-directory: mango_genetic

      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_GENETIC_TOKEN }} dist/*
        working-directory: mango_genetic

