name: mango full unit testing

on:
  push:
    branches:
      - master
      - development

jobs:
  unit-testing:
    name: Run all unit test suites
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 21
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./all-requirements.txt
    - name: Run base unit testing
      run: |
        coverage run --source=. --rcfile=./mango_base/.coveragerc -m unittest discover -t mango_base -s mango_base/mango/tests
        coverage report -m
    - name: Run time series unit testing
      run: |
        coverage run -a --source=. --rcfile=./mango_time_series/.coveragerc -m unittest discover -t mango_time_series -s mango_time_series/mango/tests
        coverage report -m
        coverage xml
    - name: Upload coverage to artifact
      if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

  upload-coverage:
    name: Upload coverage to Codecov
    needs: unit-testing
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact with the coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: ./
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}


  setup-testing:
    name: Build the library to test that it gets correctly built
    needs: unit-testing
    defaults:
      run:
        working-directory: ./mango_time_series
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install wheel
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build binary wheel and source tarball
        run: |
          python -m build